# Pertemuan 2 - Praktikum Analisis Dataset Titanic

Nama: Krisna Naufal Azhar Suhendar

Deskripsi: Notebook ini berisi jawaban Q1–Q6 menggunakan Pandas & NumPy.

In [13]:
import pandas as pd
import numpy as np

## Load Dataset

In [21]:
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df = pd.read_csv(url)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## Q1: Jumlah baris, kolom, dan nama kolom

In [27]:
df.shape, df.columns

((891, 12),
 Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
        'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
       dtype='object'))

## Q2: Missing values

In [16]:
missing = df.isnull().sum()
persen = (missing / len(df)) * 100
pd.DataFrame({'Missing': missing, 'Persen (%)': persen})

             Missing  Persen (%)
PassengerId        0    0.000000
Survived           0    0.000000
Pclass             0    0.000000
Name               0    0.000000
Sex                0    0.000000
Age              177   19.865320
SibSp              0    0.000000
Parch              0    0.000000
Ticket             0    0.000000
Fare               0    0.000000
Cabin            687   77.104377
Embarked           2    0.224467

## Q3: Persentase penumpang selamat

In [28]:
df['Survived'].mean() * 100

np.float64(38.38383838383838)

## Q4: Wanita kelas 1

In [18]:
wanita_kelas1 = df[(df['Sex'] == 'female') & (df['Pclass'] == 1)]
wanita_kelas1.shape[0], wanita_kelas1['Age'].mean()

(94, np.float64(34.61176470588235))

## Q5: Survival rate per kelas

In [19]:
df.groupby('Pclass')['Survived'].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

## Q6: Analisis tambahan (Gender)

In [20]:
df.groupby('Sex')['Survived'].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64